apiVersion: ENC[AES256_GCM,data:UCI=,iv:O5xfR9dzDf2zuGaapli2zbS2ZWmUSZ6t32IReoclYEM=,tag:xGpxh/0zScdKzdl3p2YiQw==,type:str]
data:
    index.html: ENC[AES256_GCM,data:ptzKoA==,iv:9UQfLXf0n/tyybArgNqw/Sl6sV67hmz6L3u9O7nPUv0=,tag:YNjdYRgvAvTS4cS6hpHL+g==,type:str]
kind: ENC[AES256_GCM,data:3tnJ/Idb,iv:7RsrL9eu4WldtGxNmV1kFskXmMFcjkh+2sa4xuejl5o=,tag:V/Q4zUtfZ6wOVN+xBcxYRQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iUlQBg==,iv:jzkvI21mXrp1CkXHSIRtCVJYK0SonMzITiFRHfYdUMQ=,tag:UMCvNWmN1v09KXYMi4hKdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-07-20T13:48:28Z'
    mac: ENC[AES256_GCM,data:1A8h4tyLrv9QWaE+R0Z4+Uh4y6IFphXyAgfxYyo1c7aGvIJ3xNughUYev0SAsfV8hpPptKR0VOxkcQ7kDc/fkRV2YINgp9WQuf7zgSL+ekxkrTeESHpxGOx8+W5pqiwmWZQRQES+CXaBzdugnf6M8j66c+oFe5ht28YvQjPKYYA=,iv:rkC1CRP4g4Rckutf9E497wPXO2iuA1fIwPNoyneVuQA=,tag:EbFq/PnJGxX21y+J10YCpQ==,type:str]
    pgp:
    -   created_at: '2020-07-20T13:48:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/oywAFalZNXAQ/+LP5ZeI+uVxqgeEeqPAQabk0MF0RaicCVtXvWZeT15I0i
            aqhofxi92mcK7x4GLwwBYT0PgSlQsNg9E/btQrhpzf8XUo/9S77LH4PghtwFY9/7
            Zxeyn5CdE5pKWf98pmVkS7AH7vnKY/PoSjRZ9RnPsq2OcLBiUoSMHmNdvRsy7Dx5
            AdouP+rRCDCjZ1sIi+l5ikPJPCZaJoyvNfvsizsh2DeM4l1gjmNvldOdBc6vNwrs
            +GHKTuaV73ZReDGasPTfB9BktmpD3o3aeQ6hvXZEnw2hkKjYm92FB3x/xdirFnpK
            rO0E8kDEDqGOsnQXmHrC6YfN75A0lFPzGhJOX59mVufTGjcE83Mrf3UEXmF2Z5g9
            Bv8r8A99lkkHOMtb5W9vwmHtGeBnR0BnIxjWoNo/8N9Dhz+2GAIwIsJ697Q1IuSu
            thCAShas9y7rj6/dp4akhlgynIlbyHPezycDiwGvP73sVTIcMHjh5q+sGyJgp0dJ
            iauebWTod3iT0JYze2ju80sTaj2Y9+ry/pHs8e/v4b8e3P65Wmx2jWS3fOdq+h3e
            VDnJbm+HlixSWKblQjeBc/k5pMKijcgYCrhhDOBo4fEzSe9vNmkEhqSSR1VlGf1D
            SCLMP4Nw7LcyufUZJ1krPRVBdx2IXP28U7rcBeovOX3/FrT7LLHd7EbiCQ9iLuzS
            XgElRdKo+ZbrglygHr7Ob5VvKG4eHWqPVeMpClBIvIk4vUDH2VTrYyt00s+VK2A6
            wlaxZuNMYJVIve94IHxHbKdzalM3U+cUXV5qvH5aZ7zkAwmO/4dizls1oNOKb4w=
            =5pLc
            -----END PGP MESSAGE-----
        fp: 2D74AFF093C81D32E8F12AB77F781FF49F045797
    unencrypted_suffix: _unencrypted
    version: 3.6.0
